name: PR Pipeline

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Run tests
        run: dotnet test --no-restore --verbosity normal
        
      - name: Run code linting
        run: dotnet format --verify-no-changes
        continue-on-error: true
      
      - name: Check code coverage
        run: dotnet test --collect:"XPlat Code Coverage"
  
      - name: Run security scan
        uses: github/codeql-action/init@v1
        with:
          languages: csharp
